language: node_js

node_js:
  - 11
  - 10

install:
  - npm install

script:
    - touch config.js
    - echo "module.exports = {
      prefix: '+',
      token: '',
      owners: [],
      allowMentionPrefix: true,

      webhooks: { // First item is ID, second is token
        log: ['', ''],
        command: ['', ''],
        error: ['', '']
      },
      reportChannel: ''

    }
  " > config.js
  - node bot.js
